# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.ssh.forward_agent = true

  config.vm.provision :host_shell do |host_shell|
    host_shell.inline = '~/.vagrant.d/dependency_check.rb'
    host_shell.abort_on_nonzero = true
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = '~/.vagrant.d/berks-cookbooks'
    chef.arguments = '-l debug'
    chef.verbose_logging = true

    chef.json = {
      devenv: {
        packages: ['git', 'silversearcher-ag', 'vim-nox', 'ack-grep', 'ruby1.9.1-dev', 'htop', 'tree'],
        users: {
          vagrant: {
            repo: 'git@github.com:jcnnghm/dotfiles.git',
            shell: 'zsh'
          }
        }
      }
    }

    chef.run_list = [
      'recipe[devenv]',
    ]
  end
end
